Sprint 7 solution in file manager
ToxicCritic/java-kanban pull request #2
Opened 2024-08-17 14:07 UTC by ToxicCritic

2024-08-18 10:39 UTC, tomattman requested changes
комментарии в коде

2024-08-18 10:39 UTC, tomattman commented on src/managers/Managers.java
> +        return new FileBackedTaskManager( new File(System.getProperty("user.dir"), "tasks.csv"));
Рекомендую вынести имя файла в константу

2024-08-18 10:39 UTC, tomattman commented on src/managers/taskManager/FileBackedTaskManager.java
> +    public static class ManagerSaveException extends RuntimeException {
почему бы не создать отдельный класс для ошибки
так как это RuntimeException работать скорее всего мы будем не только внутри этого класса, а следовательно это уже глобальный класс

2024-08-18 10:39 UTC, tomattman commented on src/managers/taskManager/FileBackedTaskManager.java
> +    public void save() {
этот метод только для внутреннего пользования, модификатор должен быть private

2024-08-18 10:39 UTC, tomattman commented on src/managers/taskManager/FileBackedTaskManager.java
> +    public FileBackedTaskManager(File file) {
Используя этот метод класс может быть создан без чтения из файла, и таким образом мы можем потерять данные, рекомендую сделать этот конструктор приватным, и тем самым оставить возможность создать объект класса только через статический метод

2024-08-18 10:39 UTC, tomattman commented on src/managers/taskManager/FileBackedTaskManager.java
> +                writer.write(taskToString(task) + "\n");
перевод на новую строку можно добавить как  часть метода taskToString

2024-08-18 10:39 UTC, tomattman commented on src/managers/taskManager/FileBackedTaskManager.java
> +            writer.write(historyToString());
Кажется вам уже не надо сохранять историю в файл, но круто

2024-08-18 10:39 UTC, tomattman commented on src/managers/taskManager/FileBackedTaskManager.java
> +                    if (task instanceof Epic) {
InstanceOf не ООП вместо него стоит использовать методы и их перегрузку по типу

2024-08-18 10:39 UTC, tomattman commented on src/managers/taskManager/FileBackedTaskManager.java
> +        if (task instanceof Subtask) {
и снова, не ооп подход, 
использую перегрузку методов

2024-08-18 10:39 UTC, tomattman commented on src/managers/taskManager/FileBackedTaskManager.java
> +                    if (task instanceof Epic) {
второй способ, сделать метод, который будет принимать строку, и возвращать тип таска в ней

2024-08-18 10:39 UTC, tomattman commented on src/managers/taskManager/FileBackedTaskManager.java
> +            case "TASK":
лучше создать перечисление для типов тасков, и использовать его, меньше шансов на ошибку

2024-08-18 10:39 UTC, tomattman commented on src/managers/taskManager/FileBackedTaskManager.java
> +public class FileBackedTaskManager extends InMemoryTaskManager {
тут не хватает сохранения данных в файл

2024-08-18 10:39 UTC, tomattman commented on src/managers/taskManager/FileBackedTaskManager.java
> +public class FileBackedTaskManager extends InMemoryTaskManager {
при выполнении действий, изменяющих состояние менеджера, необходимо все сохранять в файл

2024-08-18 10:39 UTC, tomattman commented on src/managers/taskManager/FileBackedTaskManager.java
> +    public void save() {
обычно есть простое правило, если используется интерфейс, и по интерфейсу, то все что не в интерфейсе, должно быть закрыто

2024-08-18 10:39 UTC, tomattman commented on src/tasks/Epic.java
> +    @Override
зачем переопределять эти методы?
обычно они имеют стандартный формат и не используются ни для чего кроме как вывести значение в логах

2024-08-18 10:39 UTC, tomattman commented on src/managers/taskManager/FileBackedTaskManagerTest.java
> +package managers.taskManager;
тесты обычно хранятся в отдельной папке
в папке src/test/
дальше повторяется полная структура пакетов из основного проекта, и уже в месте соответствующем тестируемому классу, лежит тестовый класс

2024-08-18 10:39 UTC, tomattman commented on src/managers/taskManager/FileBackedTaskManagerTest.java
> +package managers.taskManager;
потому что обычно тестовая папке не включается в билд проекта, т.е. они прогоняются в процессе сборки, но их классы, не включаются в исполняемый файл

2024-08-21 11:55 UTC, tomattman requested changes
Привет, есть еще пара нюансов 
плюс по пакетам
обычно выделяют следующую структуру папок и пакетов 
папка src  - в ней весь код
в ней папки main -в ней код основной код приложения, то что выполняет основные действия
и папка test -в ней код только для тестов (чаще всего он выполняется только при сборки и не включается в финальную сборку
в папке main про структуру пакетов вам расскажут позже, но обычно есть основной пакет, с именем проекта, потому что если что то будет без пакета, ты не сможешь его импортировать
в папке test точно такая же стуруктура пакетов как и в папке main и если мы тестируем класс который находится в пакете managers то его тест должен быть тоже в пакете managers

Если что то еще не понятно пиши

2024-08-21 11:55 UTC, tomattman commented on src/managers/taskManager/FileBackedTaskManager.java
> +                    task.addToManager(manager);
Вот тут ты перемудрил, стоит убрать этот метод из таска
и как сделать лучше есть несколько вариантов, рекомендую следующий
сделать метод, private TaskType getTaskType(String line) который будет возвращать тип таска, 
и тут можно сделать так
Task task = taskFromString(line);
switch(getTaskType(line)){
   case TASK: tasks.put(task.getIf(), task); break;
//и так далее

2024-08-21 11:55 UTC, tomattman commented on src/tasks/Task.java
> +    public String toCsvString() {
стоит удалить этот метод из таска и всех наследников и предыдущий тоже, формирование строки и добавление в менеджер это не обязанность класса модели, класс модель по хорошему ничего не должен знать кроме своей структуры,
Теперь про перегрузку методов, ты кажется перепутал перегрузку и переопределение
вот статья
https://timeweb.cloud/tutorials/java/peregruzka-i-pereopredelenie-metodov-v-java-primery

2024-08-21 16:07 UTC, ToxicCritic commented
Спасибо за конкретные и понятные замечания!

2024-08-22 12:22 UTC, tomattman requested changes
Есть еще парочка моментов на исправление

2024-08-22 12:22 UTC, tomattman commented on src/main/managers/taskManager/FileBackedTaskManager.java
> +                            manager.createTask(task);
тут еще одна проблема, методы createTask, createSubtask, createEpic изменяют идентификатор таска, поэтому такой способ не подходит, ибо теряется связь, тут надо класть в мапу напрямую

и второй момент тоже связанный с этим, когда ты считаешь из файла, счетчик идентификаторов будет равен начальному значению, и значит потом при добавлении новых тасок, он может переписывать старые значения, надо с этим так же разобраться

Так как у вас есть тесты, предлагаю написать следующие тесты:
1) записываем в файловый менеджер, таск, потом эпик, потом сабтаск, потом снова таск, потом удаляем первый таск, и создаем новый таск менеджер к этому же файлу, и надо проверить что связь не потерялась
2) в принципе первый тест покроет этот случай но можно отдельным тестом, создаешь три таска, удаляешь первый, и смотришь что после создания нового таск менеджера к этому файлу,  в нем будет два таска с теми же значениями и идентификаторами
3) создаешь один таск, создаешь новый менеджер к тому же файлу, добавляешь в новый менеджер еще один таск, смотришь что в новом менеджере два таска и правильные
4) создаешь два таска удаляешь первый, создаешь новый менеджер к этому же файлу, добавляешь два таска, смотришь что в менеджере три таска с нужными значениями (и да этот случай отличается от предыдущего)

2024-08-22 12:22 UTC, tomattman commented on src/main/managers/taskManager/FileBackedTaskManager.java
> +                        case EPIC:
ах да, тут есть еще одна проблема, напрямую я ее тебе не напишу, но скажу тест, как ее увидеть, если не поймешь проблему, пиши в сообщения, подскажу что за она

как вопроизвести
создаешь эпик, создаешь ему парочку сабтасков, создаешь новый менеджер к этому же файлу, вызываешь метод на получение всех сабтасков по эпику

2024-08-24 19:41 UTC, tomattman approved these changes
Принято

2024-08-24 19:41 UTC, tomattman commented on src/main/managers/taskManager/FileBackedTaskManager.java
> +                            Epic parentEpic = manager.getEpicById(subtask.getEpicId());
вот тут я бы рекомендовал сделать это отдельным циклом, после основного, вдруг сабтаск считается раньше эпика

2024-08-24 21:36 UTC, merged